require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # update the return value of this method accordingly.
  # e.g. user = User.create! valid_attributes
  def valid_attributes
    {
      # comment out because of protection for mass assignment
      #"provider"    => "provider_sample",
      #"provider_uid"         => 100000000,
      #"auth_token" => "token_example",
      "name"     => "name_sample",
      "email"    => "example@example.com",
      "birthday" => "2011-01-11",
      "screen_name" => "nickname_example",
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  context "when user is NOT logged in" do
    it "allow some actions and reject others"
  end

  context "when user is logged in" do
    before { @user = FactoryGirl.create(:user) }

    describe "GET index" do
      context "without search params" do
        it "assigns all users as @users" do
          get :index, {}, valid_session
          assigns(:users).should eq([@user])
        end
      end

      context "with search params" do
        it "assigns searched users as @users" do
          get :index, {search: { location: "tokyo"} }, valid_session
          assigns(:users).should eq([@user])
        end
      end
    end

    describe "GET show" do
      it "assigns the requested user as @user" do
        get :show, {:id => @user.to_param}, valid_session
        assigns(:user).should eq(@user)
      end
    end

    describe "GET edit" do
      before do
        @all_languages = FactoryGirl.create_list(:language, 2)
        @user.languages = @all_languages
        @user_languages = @user.languages

        FbGraph::User.stub(:fetch).and_return(User.new)
        User.any_instance.stub(:likes).and_return(Array.new)
        get :edit, {:id => @user.to_param}, valid_session
      end

      it "assigns @user" do
        assigns(:user).should_not nil
      end
      it "assigns @user_languages" do
        assigns(:user_languages).should eq @user_languages
      end
      it "assigns @all_languages" do
        assigns(:all_languages).should eq @all_languages
      end
      it "assigns @likes" do
        assigns(:likes).should_not nil
      end
    end

    describe "POST create" do
      describe "with any params" do
        it "reject because we only accept Facebook OAuth" do
          post :create, {}, valid_session
          response.should redirect_to(root_path)
        end
      end
    end

    describe "PUT update" do
      context "with valid params" do
        it "updates the requested user" do
          # Assuming there are no other users in the database, this
          # specifies that the User created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          User.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => @user.to_param, :user => {'these' => 'params'}}, valid_session
        end

        it "assigns the requested user as @user" do
          put :update, {:id => @user.to_param, :user => valid_attributes}, valid_session
          assigns(:user).should eq(@user)
        end

        it "redirects to the user" do
          put :update, {:id => @user.to_param, :user => valid_attributes}, valid_session
          response.should redirect_to(@user)
        end
      end

      context "with invalid params" do
        it "assigns the user as @user" do
          # Trigger the behavior that occurs when invalid params are submitted
          User.any_instance.stub(:save).and_return(false)
          put :update, {:id => @user.to_param, :user => {}}, valid_session
          assigns(:user).should eq(@user)
        end

        it "re-renders the 'edit' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          User.any_instance.stub(:save).and_return(false)
          put :update, {:id => @user.to_param, :user => {}}, valid_session
          response.should render_template("edit")
        end
      end

      context "with empty language" do
        it "redirect successfully" do
          put :update, {:id => @user.to_param, :user => valid_attributes, languages: [""]}, valid_session
          response.should redirect_to(@user)
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested user" do
        expect {
          delete :destroy, {:id => @user.to_param}, valid_session
        }.to change(User, :count).by(-1)
      end

      it "redirects to the users list" do
        delete :destroy, {:id => @user.to_param}, valid_session
        response.should redirect_to(users_url)
      end
    end
  end
end
